[package]
name = "image-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.0.26", features = ["derive"] }
image = "0.24.5"
inquire = "0.5.2"
spinners = "4.1.0"
